[BE] JWT 토큰 발급받기 /#46
42Nuts/Transcendence pull request #52
Opened 2024-02-08 08:11 UTC by GCgang

## 🤔 PR 유형
- [x] Feat: 새로운 기능 추가
- [ ] Fix: 버그 수정
- [ ] Docs: 문서 수정
- [ ] Style: 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] Refactor: 코드 리팩토링
- [x] Test: 테스트 추가, 테스트 리팩토링
- [x] Chore: 빌드 부분 혹은 패키지 매니저 수정
- [ ] Comment: 주석 추가 및 수정
- [ ] Rename: 파일 혹은 폴더명 수정
- [ ] Remove: 파일 혹은 폴더 삭제

## 🔄 변경사항
- [x] requirements.txt 에 djangorestframework-simplejwt==5.3.1 추가
- [x] config/settings.py 에 REST_FRAMEWORK, SIMPLE_JWT 추가
- [x] user 모델에 access token, refresh token 삭제
- [x] auth 인증 후 DRF 이용하여 JWT 토큰 받은 값 리턴

## ✅ PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. Commit message convention 참고
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

##  📷 스크린샷
- access token 및 refresh token 발급받은 모습

<img width="960" alt="Screen Shot 2024-02-08 at 5 09 48 PM" src="https://github.com/42Nuts/Transcendence/assets/85366633/f695e3f7-484b-4487-a936-80218e23c45a">

2024-02-08 10:46 UTC, leechan02 requested changes
branch 충돌납니다. 수정부탁드려요.🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

2024-02-09 02:02 UTC, leechan02 commented
어떤 버전 명령어? 때문에 충돌 났던거로 기억하는데, 그냥 그 merge 버튼에 main branch랑 충돌난다고 써져있었어유. 아마 pr 날리기 전에 main에서 pull 하고 pr 날려야 할거에유

2024-02-10 05:19 UTC, leechan02 commented
<img width="959" alt="image" src="https://github.com/42Nuts/Transcendence/assets/89778914/b215f087-a205-4f18-b2b3-40c8a14a13be">
요거 무시하고 리뷰 남길까여, 아님 그냥 다시 하실건가유?

2024-02-10 05:33 UTC, GCgang commented
> <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/89778914/303817656-b215f087-a205-4f18-b2b3-40c8a14a13be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDM0MzksIm5iZiI6MTcwNzU0MzEzOSwicGF0aCI6Ii84OTc3ODkxNC8zMDM4MTc2NTYtYjIxNWYwODctYTIwNS00ZjE4LWIyYjMtNDBjOGExNGExM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA1MzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNDNhNmYzMTU3NTNiODQ0NGQzMzk1OWEyNmU3MDE5ZjU1ZDg2YTY5OTU5NGMxZmEwODllODk3MjE3MmE5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KYrL5s71WzAjPNmg5GNa4W2ezCYQ76KP5KUpWIgPimY"> 요거 무시하고 리뷰 남길까여, 아님 그냥 다시 하실건가유?

해놨습돠 :)

2024-02-10 05:36 UTC, leechan02 approved these changes
code가 뭔 말인지 다 알아야할 것 같은 느낌이 들지만, 뭔 말인지는 하나도 모르겠지만, 제가 뭔말을 하는지도 모르겠지만, 수고 하셨습니당.

2024-02-13 02:19 UTC, gitubanana approved these changes
좀 더 정교하게 하려면, Front 코드가 필요할 것 같네요.
Back 코드는 잘 작동하네요.
수고하셨습니당~!

2024-02-13 02:19 UTC, merged